### ISSUE TITLE
Meeting End date can be set to a date/hour prior to the Start date

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-meeting#78] opened 2020-12-09 15:02 UTC
Steps to reproduce:

1. Create a new meeting with a selected Start Date and time eg. "08/12/2020 16:00"
2. Choose an End Date prior to the Start Date eg. "03/12/2020 09:30"

Expected results: The user isn't allowed to select a date/hour prior to the Start Date.

Actual results: The user can select any date and hour, with the Date picker or by writing in the text input field. The meeting duration is not calculated properly also.

![MeetingDuration](https://user-images.githubusercontent.com/40691112/101646368-1d5ec480-3a40-11eb-906f-0ece1a5686d5.png)

Environment: XWiki 12.6.5 with Chrome 87, Meeting Application (Pro) 1.11

**It appears that [issue 65](https://github.com/xwikisas/application-meeting/issues/65) wasn't fixed.**

**Comment by mflorea** [comment] 2020-12-10 08:34
@ignatescustefan please look at this ASAP. If the issue was not fixed in #65 then I'd like to know why. The steps to reproduce indicated by @ane-gabriela are fairly simple so how come you didn't catch this? Thanks.

**Comment by ignatescustefan** [comment] 2020-12-10 09:55
Hello! I first tested the bug for XWiki 9.11 and it reproduced. After that, I fixed that and tested it on the minimum supported version. Now, I did not take into consideration the fact that the fix should be also tested on the reported version. Looking now on it.

![image](https://user-images.githubusercontent.com/50322733/101752252-f8b72b00-3ad9-11eb-9592-2ac36548617a.png)

**Comment by mflorea** [comment] 2020-12-10 13:02
> I fixed that and tested it on the minimum supported version.

That's very good. Please double check if the issue is fixed on 9.11 with the released version of the Meeting application.

> the fix should be also tested on the reported version.

I understand. Indeed, it would be good to test also on the XWiki version where the issue was reported. Let us know if you can reproduce on 12.6.5. Thanks.

**Comment by ignatescustefan** [comment] 2020-12-22 14:23
It was needed to listen to the `dp.change` event, because the `change` event is not triggered anymore on the new Date Time Picker.
User interaction after the fix:
https://user-images.githubusercontent.com/50322733/102897000-01abe300-4470-11eb-987f-e372cfbdbb4b.mp4

**Closed** 2020-12-22 14:28 UTC
Labels: Priority: Blocker, Type: Bug
